backend/models/Prompt.php
<?php

namespace backend\models;

use common\models\prompt\ForWhomPrompt;
use common\models\prompt\PageType;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "prompt".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $page_type_id
 * @property integer $for_whom_prompt_id
 * @property string $video_link
 * @property string $title
 * @property string $text
 *
 */
class Prompt extends ActiveRecord
{

    /**
     *
     */
    const ACTIVE = 1;
    /**
     *
     */
    const BLOCKED = 0;

    const ALL = 2;

    public static $PromptStatus = [
        self::ACTIVE => 'Активированная',
        self::BLOCKED => 'Заблокированная',
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'prompt';
    }

    public static function find()
    {
        return new PromptQuery(get_called_class());
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'page_type_id', 'for_whom_prompt_id', 'text', 'title'], 'required'],
            [['status', 'page_type_id', 'for_whom_prompt_id'], 'integer'],
            [['text'], 'string'],
            [['video_link', 'title'], 'string', 'max' => 255],
            [['page_type_id'], 'exist', 'targetClass' => PageType::className(), 'targetAttribute' => 'id',],
            [['for_whom_prompt_id'], 'exist', 'targetClass' => ForWhomPrompt::className(), 'targetAttribute' => 'id',],
            [['status'], 'validateStatus'],
        ];
    }

    public function validateStatus()
    {
        if ($this->status == Prompt::ACTIVE) {
            $promptsQuery = (new PromptHelper())->getPrompts(Prompt::ACTIVE, $this->for_whom_prompt_id, $this->page_type_id);

            if (count($promptsQuery) >= 1 && $promptsQuery[0]['id'] !== $this->id) {
                $this->addError('status');
            }
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Статус',
            'page_type_id' => 'Страница',
            'for_whom_prompt_id' => 'Для кого',
            'video_link' => 'Видео',
            'title' => 'Заголовок',
            'text' => 'Текст',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPageType()
    {
        return $this->hasOne(PageType::className(), ['id' => 'page_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getForWhomPrompt()
    {
        return $this->hasOne(ForWhomPrompt::className(), ['id' => 'for_whom_prompt_id']);
    }

    public function getNewVideoLink()
    {
        // https://vimeo.com/156520621
        // https://player.vimeo.com/video/156520621?title=0&byline=0&portrait=0

        $url = 'https://player.vimeo.com/video/';
        $settings = '?title=0&byline=0&portrait=0';
        $id = preg_replace("/[^0-9]/", '', $this->video_link);

        return $url . $id . $settings;
    }
}

backend/models/PromptHelper.php
<?php
/**
 * Created by PhpStorm.
 * User: valik
 * Date: 11.02.2016
 * Time: 16:34
 */

namespace backend\models;


class PromptHelper extends Prompt
{
    public function getPrompts($status, $forWhomPromptId, $pageTypeId, $page = false)
    {
        $query = static::find();

        $query
            ->byStatus($status)
            ->byForWhomPromptId($forWhomPromptId)
            ->byPage($pageTypeId);

        $promptQuery = $query->all();

        if ($page === true) {
            if (!empty($promptQuery)) {
                $prompt = new Prompt(reset($promptQuery));
                if ($prompt !== null) {
                    return $prompt;
                }
            }
            return null;
        }

        return $promptQuery;
    }
}

backend/controllers/PromptController.php
<?php

namespace backend\controllers;

use backend\components\BackendController;
use backend\models\Prompt;
use backend\models\PromptHelper;
use backend\models\PromptSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;


/**
 * Class PromptController
 * @package backend\controllers
 */
class PromptController extends BackendController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Prompt models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PromptSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Prompt model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Prompt model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Prompt();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->video_link) {
                $model->video_link = $model->getNewVideoLink();
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::$app->session->setFlash('error', 'Не удалось создать подсказку. Для данного типа компании на выбранной странице активирована другая подсказка ');

                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Prompt model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->video_link) {
                $model->video_link = $model->getNewVideoLink();
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::$app->session->setFlash('error', 'Не удалось создать подсказку. Для данного типа компании на выбранной странице активирована другая подсказка ');

                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Prompt model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionActivate($id)
    {
        $model = $this->findModel($id);

        $promptsQuery = (new PromptHelper())->getPrompts(Prompt::ACTIVE, $model->for_whom_prompt_id, $model->page_type_id);

        if (count($promptsQuery) === 1) {
            $newPrompts = $this->findModel($promptsQuery[0]['id']);

            if ($newPrompts !== null) {
                $newPrompts->status = Prompt::BLOCKED;
                if ($newPrompts->save(true, ['status'])) {
                    $model->status = Prompt::ACTIVE;
                    if ($model->save(true, ['status'])) {
                        Yii::$app->session->setFlash('success', 'Подсказка активирована');

                        return $this->redirect(['index']);
                    }
                }
            }
        } elseif (count($promptsQuery) < 1) {
            $model->status = Prompt::ACTIVE;
            if ($model->save(true, ['status'])) {
                Yii::$app->session->setFlash('success', 'Подсказка активирована');

                return $this->redirect(['index']);
            }
        }
        Yii::$app->session->setFlash('error', 'Не удалось активировать подсказку');

        return $this->redirect(['index']);
    }

    public function actionBlock($id)
    {
        $model = $this->findModel($id);

        $model->status = Prompt::BLOCKED;

        if ($model->save(true, ['status'])) {
            Yii::$app->session->setFlash('success', 'Подсказка заблокирована');

            return $this->redirect(['index']);
        }
        Yii::$app->session->setFlash('error', 'Не удалось заблокировать подсказку');

        return $this->redirect(['index']);
    }

    /**
     * Finds the Prompt model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Prompt the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Prompt::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/prompt/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\models\Prompt;
use common\models\prompt\PageType;
use yii\helpers\ArrayHelper;
use dosamigos\tinymce\TinyMce;
use common\widgets\FormButtonsWidget;
use common\models\prompt\ForWhomPrompt;

/* @var $this yii\web\View */
/* @var $model backend\models\Prompt */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="prompt-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status')
        ->dropDownList(Prompt::$PromptStatus); ?>

    <?= $form->field($model, 'page_type_id')
        ->dropDownList(ArrayHelper::map(PageType::find()->all(), 'id', 'name')); ?>

    <?= $form->field($model, 'for_whom_prompt_id')
        ->dropDownList(ArrayHelper::map(ForWhomPrompt::find()->all(), 'id', 'name')); ?>

    <?= $form->field($model, 'video_link')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'text')->widget(TinyMce::className(), [
        'options' => [
            'rows' => 20,
        ],
        'language' => 'ru',
        'clientOptions' => [
            'menubar' => false,
            'statusbar' => false,
            'toolbar' => [
                'undo redo | hr bullist numlist table | link unlink | charmap',
                'bold italic underline strikethrough | subscript superscript | fontsizeselect forecolor backcolor | alignleft aligncenter alignright alignjustify',
            ],
            'plugins' => join(',', [
                'preview', 'paste', 'contextmenu', 'autoresize',
                'textcolor',
                'hr', 'table',
                'charmap',
                'link',
            ]),
            'external_plugins' => [],

            'contextmenu' => 'cut copy paste | link image inserttable | cell row column deletetable',
            'paste_as_text' => true,
            'resize' => 'both',
            'object_resizing' => 'img',
            'autoresize_max_height' => 300,
            'relative_urls' => false,
            'convert_urls' => true,
        ],
    ]); ?>

    <?= FormButtonsWidget::widget(); ?>

    <?php ActiveForm::end(); ?>

</div>

backend/views/prompt/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Prompt */

$this->title = 'Создать подсказку';
$this->params['breadcrumbs'][] = ['label' => 'Prompts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prompt-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/prompt/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use backend\models\Prompt;
use common\models\prompt\PageType;
use common\models\prompt\ForWhomPrompt;
use frontend\modules\documents\components\FilterHelper;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $searchModel backend\models\PromptSearch */

$this->title = 'Подсказки';
$this->params['breadcrumbs'][] = $this->title;
$mass = [];
$mass[null] = 'Все';
$mass += Prompt::$PromptStatus;
?>
<div class="portlet box">
    <div class="btn-group pull-right title-buttons">
        <?= Html::a('<i class="fa fa-plus"></i> Добавить', Url::to(['create']), ['class' => 'btn yellow']); ?>
    </div>
    <h3 class="page-title"><?= $this->title; ?></h3>
</div>

<div class="portlet box darkblue">
    <div class="portlet-title">
        <div class="caption">
            <?= $this->title; ?>
        </div>
    </div>
    <div class="portlet-body accounts-list">
        <div class="table-container" style="">
            <div
                class="dataTables_wrapper dataTables_extended_wrapper">
                <?= common\components\grid\GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'tableOptions' => [
                        'class' => 'table table-striped table-bordered table-hover dataTable documents_table',
                    ],

                    'headerRowOptions' => [
                        'class' => 'heading',
                    ],

                    'options' => [
                        'style' => 'overflow-x: auto;',
                    ],
                    'pager' => [
                        'options' => [
                            'class' => 'pagination pull-right',
                        ],
                    ],
                    'layout' => "<div class=\"scroll-table-wrapper\">{items}</div>\n{pager}",
                    'columns' => [
                        [
                            'attribute' => 'id',
                            'headerOptions' => [
                                'width' => '3%',
                            ],
                            'format' => 'raw',
                            'value' => function (Prompt $data) {
                                return Html::a($data->id, Url::toRoute(['view', 'id' => $data->id]));
                            },
                        ],
                        [
                            'attribute' => 'page_type_id',
                            'headerOptions' => [
                                'width' => '20%',
                            ],
                            'format' => 'raw',
                            'value' => function (Prompt $data) {
                                return PageType::findOne($data->page_type_id)->name;
                            },
                        ],
                        [
                            'attribute' => 'for_whom_prompt_id',
                            'filter' => FilterHelper::getFilterArray(ForWhomPrompt::find()->all(), 'id', 'name', true, false),
                            'headerOptions' => [
                                'width' => '6%',
                            ],
                            'format' => 'raw',
                            'value' => function (Prompt $data) {
                                return ForWhomPrompt::findOne($data->for_whom_prompt_id)->name;
                            },
                        ],
                        [
                            'attribute' => 'title',
                            'headerOptions' => [
                                'width' => '40%',
                            ],
                            'format' => 'raw',
                            'value' => function (Prompt $data) {
                                return $data->title;
                            },
                        ],
                        [
                            'attribute' => 'video_link',
                            'headerOptions' => [
                                'width' => '4%',
                            ],
                            'format' => 'raw',
                            'value' => function (Prompt $data) {
                                if (!empty($data->video_link)) {
                                    return Html::a('<span class="glyphicon glyphicon-film"></span>', $data->video_link, [
                                        'target' => '_blank',
                                    ]);
                                }

                                return 'Нет';
                            },
                        ],
                        [
                            'attribute' => 'status',
                            'filter' => FilterHelper::getPromptStatusArray(),
                            'headerOptions' => [
                                'width' => '15%',
                            ],
                            'format' => 'raw',
                            'value' => function (Prompt $data) {
                                return Prompt::$PromptStatus[$data->status];
                            },
                        ],
                        [
                            'class' => \yii\grid\ActionColumn::className(),
                            'template' => '{activate} {block} {update} {delete}',
                            'buttons' => [
                                'activate' => function ($url, Prompt $data) {
                                    if ($data->status == Prompt::BLOCKED) {
                                        return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, [
                                            'title' => Yii::t('yii', 'Активировать'),
                                            'aria-label' => Yii::t('yii', 'Активировать'),
                                            'data-confirm' => Yii::t('yii', 'Вы действительно хотите активировать эту подсказку?'),
                                            'data-method' => 'post',
                                            'data-pjax' => '0',
                                        ]);
                                    }
                                },
                                'block' => function ($url, Prompt $data) {
                                    if ($data->status == Prompt::ACTIVE) {
                                        return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, [
                                            'title' => Yii::t('yii', 'Заблокировать'),
                                            'aria-label' => Yii::t('yii', 'Заблокировать'),
                                            'data-confirm' => Yii::t('yii', 'Вы действительно хотите заблокировать эту подсказку?'),
                                            'data-method' => 'post',
                                            'data-pjax' => '0',
                                        ]);
                                    }
                                },
                            ],
                            'urlCreator' => function ($action, $model, $key, $index) {
                                $url = 0;
                                if ($action === 'activate') {
                                    $url = '/prompt/activate';
                                } elseif ($action === 'block') {
                                    $url = '/prompt/block';
                                } elseif ($action === 'delete') {
                                    $url = '/prompt/delete';
                                } elseif ($action === 'update') {
                                    $url = '/prompt/update';
                                }

                                return Url::to([$url, 'id' => $model->id]);
                            },
                        ],
                    ],
                ]); ?>
            </div>
        </div>
    </div>
</div>

backend/views/prompt/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Prompt */

$this->title = 'Обновить подсказку: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Prompts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="prompt-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/prompt/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\models\Prompt;
use common\models\prompt\PageType;
use common\models\prompt\ForWhomPrompt;

/* @var $this yii\web\View */
/* @var $model backend\models\Prompt */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Prompts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prompt-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => Prompt::$PromptStatus[$model->status],
            ],
            [
                'attribute' => 'page_type_id',
                'format' => 'raw',
                'value' => PageType::findOne($model->page_type_id)->name,
            ],
            [
                'attribute' => 'for_whom_prompt_id',
                'format' => 'raw',
                'value' => ForWhomPrompt::findOne($model->for_whom_prompt_id)->name,
            ],
            [
                'attribute' => 'video_link',
                'format' => 'raw',
                'value' => !empty($model->video_link)
                    ? Html::a('<span class="glyphicon glyphicon-film"></span>', $model->video_link, [
                        'target' => '_blank',
                    ])
                    : 'Нет',
            ],
            [
                'attribute' => 'title',
                'format' => 'raw',
                'value' => $model->title,
            ],
            [
                'attribute' => 'text',
                'format' => 'raw',
                'value' => $model->text,
            ],
        ],
    ]); ?>

</div>